routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\EnrolController;
use App\Http\Controllers\LMSController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\IndexController;
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('landingpage');
// });

Route::prefix('admin')->middleware(['auth','admin'])->group(function () {

    Route::get('/dashboard', [IndexController::class, 'index']);

    Route::resource('course', App\Http\Controllers\Admin\CourseController::class);

    Route::resource('category', App\Http\Controllers\Admin\CategoryController::class, ['only' => [
        'create', 'store', 'index'
    ]]);

    Route::resource('user', App\Http\Controllers\Admin\UserController::class);

});

Route::resource('catalog', CourseController::class, ['only' => [
    'index', 'show'
]]);

Route::get('/my', [CourseController::class, 'my'])->middleware('auth');
Route::get('/enrol/{id}', [EnrolController::class, 'enrol'])->middleware('auth');
Route::get('/', [LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/course/moodle/{id}', [LMSController::class, 'course'])->middleware('auth');
Route::get('/moodle/admin', [LMSController::class, 'admin'])->middleware('auth','verified');
Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $table = 'users';
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use GuzzleHttp\Client;
use App\Models\LmsSettings;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
			'user' => User::orderBy('id','DESC')->get(),
		];
		
		return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        $validateData = $request->validate([
			'fullname' => 'required',
			'email' => 'required',
			'password' => 'required',
		]);
		
		$name = explode(" ",$request->fullname);
		$countname = count($name);
		
		if($countname == 1){
			$firstname = $name[0];
			$lastname = "lms";
		}else{
			$firstname = $name[0];
			$lastname = $name[1];
		}
		
		$email = explode("@",$request->email);
		
		$countID = User::max('id');
		
		$api = LmsSettings::get();
		foreach($api as $getapi){}
		
		$functionuser = 'core_user_create_users';

		$client = new Client();
		$postUser = $client->request('POST', $getapi->siteurl . '/webservice/rest/server.php' . '?wstoken=' . $getapi->token . '&wsfunction='.$functionuser.'&moodlewsrestformat=json',
			array(
				'form_params' => array(
					'users' => array(
						array(
							'username' => $request->username,
							'firstname' => $firstname,
							'lastname' => $lastname,
							'email' => $request->email,
							// 'password' => $request->password,
							'password' => '1rhMJZ7k7CRoGdzSz0eN1rhMJZ7k7C^RoGdzSz0eN',
							'lang' => 'en'
						)
					)
				)
			)
		);

		$dataUser = $postUser->getBody();
		$dataUser = json_decode($dataUser);
		
		if(isset($dataUser->message)){
			return redirect()->back()->with('message', $dataUser->message);
		}else{
			$Users = new User;
			$Users->name = $request->fullname;
			$Users->email = $request->email;
			$Users->password = bcrypt($request->password);
			$Users->bpwd = $request->password;
			$Users->username = $request->username;
			$Users->level = $request->level;
			$Users->accounttype = 'manual';
			$Users->email_verified_at = date("Y-m-d h:i:s");
			$Users->idmoodle = $dataUser[0]->id;
			$Users->save();
			
			if($Users != null){
				return redirect('/admin/user')->with('success', 'Add New Data User Success');
			}
		}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {	
        $data = [
			'users' => User::where('idmoodle', $id)->first(),
		];

		return view('admin.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validateData = $request->validate([
			'fullname' => 'required',
			'email' => 'required',
			'password' => 'required',
		]);
		
		$name = explode(" ",$request->fullname);
		$countname = count($name);
		
		if($countname == 1){
			$firstname = $name[0];
			$lastname = "lms";
		}else{
			$firstname = $name[0];
			$lastname = $name[1];
		}
		
		$email = explode("@",$request->email);
		
		$countID = User::max('id');
		
		$api = LmsSettings::get();
		foreach($api as $getapi){}
		
		$Users = User::where('idmoodle', $id)->first();
		
		$function = 'core_user_update_users';
		$client = new Client();
		
		if($Users->accounttype == 'import'){
			$getUpdate= $client->request('POST', $getapi->siteurl.'/webservice/rest/server.php?wstoken='.$getapi->token.'&wsfunction='.$function.'&moodlewsrestformat=json',
				array(
					'form_params' => array(
						'users' => array(
							array(
								'id' => $id,
								'username' => $email[0].$countID,
								'firstname' => $firstname,
								'lastname' => $lastname,
								'email' => $request->email,
								'password' => $request->password,
								// 'password' => '1rhMJZ7k7CRoGdzSz0eN1rhMJZ7k7C^RoGdzSz0eN',
								'lang' => 'en'
							)
						)
					)
				)
			);
		}else{
			$getUpdate= $client->request('POST', $getapi->siteurl.'/webservice/rest/server.php?wstoken='.$getapi->token.'&wsfunction='.$function.'&moodlewsrestformat=json',
				array(
					'form_params' => array(
						'users' => array(
							array(
								'id' => $id,
								'username' => $email[0].$countID,
								'firstname' => $firstname,
								'lastname' => $lastname,
								'email' => $request->email,
								// 'password' => $request->password,
								'password' => '1rhMJZ7k7CRoGdzSz0eN1rhMJZ7k7C^RoGdzSz0eN',
								'lang' => 'en'
							)
						)
					)
				)
			);
			
		}

		$getUpdate = $getUpdate->getBody();
		$getUpdate = json_decode($getUpdate);

		if(isset($getUpdate->message)){
			return redirect()->back()->with('message', $getUpdate->message);
		}else{
			$Users->username = $request->username;
			$Users->name = $request->fullname;
			$Users->email = $request->email;
			$Users->password = bcrypt($request->password);
			$Users->save();
			
			return redirect('admin/user')->with('success', 'Update data users success');
		}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $api = LmsSettings::get();
		foreach($api as $getapi){}
		
		$function = 'core_user_delete_users';
		$client = new Client();
		
		$delUser= $client->request('POST', $getapi->siteurl.'/webservice/rest/server.php?wstoken='.$getapi->token.'&wsfunction='.$function.'&moodlewsrestformat=json',
			array(
				'form_params' => array(
					'userids' => array($id),
				)
			)
		);

		$dataDel = $delUser->getBody();
		$dataDel = json_decode($dataDel);
		
		if(isset($dataDel->message)){
			return redirect()->back()->with('message', $dataDel->message);
		}else{
			$Users = User::where('idmoodle', $id)->delete();
			return redirect('admin/user')->with('success', 'Menghapus data user berhasil');
		}
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'Create Users')

@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Create Users</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Create Users</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
	
    <!-- /.content-header -->
	<div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
                @if($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
          <form action="/admin/user" method="post">
					{{ csrf_field() }}
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Username</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="username" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Fullname</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="fullname" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Email</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="email" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Password</label>
						<div class="col-md-7">
						  <input class="form-control" type="password" name="password" placeholder="">
              <small class="text-danger">*Password harus memiliki minimal 1 huruf kapital, 1 huruf kecil dan simbol (*, -, # dll..)</small>
						</div>
					</div>          
           
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Level Users</label>
						<div class="col-md-7">
							<select class="select2" name="level" data-placeholder="Select model" style="width: 100%;">
							<option value="admin">Admin</option>
							<option value="teacher">Teacher</option>
							<option value="user">User</option>
						  </select>
						</div>
					</div>
					  
					  <div class="form-group row" style="margin-bottom: 0;">
                    <div class="col-md-7 offset-md-3">
                      <input class="btn btn-primary" type="submit" value="Save">
                    </div>
                  </div>
				</form>
              </div>
            </div><!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection
@push('script')
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
	});
  </script>
@endpush

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'Update Users')

@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Update Users</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Update Users</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
	
    <!-- /.content-header -->
	<div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 mx-auto">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
                @if($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
                <form action="/admin/user/{{$users->idmoodle}}" method="post" enctype="multipart/form-data">
                    @method('PUT')
					{{ csrf_field() }}
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Username</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="username" value="{{$users->username}}" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Fullname</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="fullname" value="{{$users->name}}" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Email</label>
						<div class="col-md-7">
						  <input class="form-control" type="text" name="email" value="{{$users->email}}" placeholder="">
						</div>
					  </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label text-md-right">Password</label>
						<div class="col-md-7">
						  <input class="form-control" type="password" name="password" placeholder="">
						</div>
					  </div>
					  <input type="hidden" name="idmoodle" value="{{$users->idmoodle}}">
					  <div class="form-group row" style="margin-bottom: 0;">
                    <div class="col-md-7 offset-md-3">
                      <input class="btn btn-primary" type="submit" value="Save">
                    </div>
                  </div>
				</form>
              </div>
            </div><!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'List Users')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">List Users</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">List Users</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
                @if(session()->has('success'))
                  <div class="alert alert-success">
                    {{ session()->get('success') }}
                  </div>
                @endif
                <table id="datatables" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Fullname</th>
                      <th>Email</th>
                      <th>Photo</th>
                      <th>Account Type</th>
                      <th>Level</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($user as $n => $getuser)
                      <tr>
                        <td>{{$n+1}}</td>
                        <td>{{$getuser->name}}</td>
                        <td>{{$getuser->email}}</td>
                        <td>
                          <img src="{{$getuser->photo}}" style="height: 50px">
                        </td>
                        <td>{{$getuser->accounttype}}</td>
                        <td><a href="/admin/change/level/{{$getuser->id}}">{{ucwords($getuser->level)}}</a></td>
                        <td>
                          @if($getuser->email_verified_at==null)
                            <a href="{{url('/admin/user/verify/'.md5($getuser->id))}}" onclick="return confirm('Anda yakin akan verifikasi data ini?')" class="badge badge-primary">Verifikasi akun</a>
                          @else
                          Verified
                          @endif
                        </td>
                        <td>
                          <a class="btn btn-info btn-sm" href="/admin/user/detail/{{$getuser->id}}">Detail</a>
                          &nbsp;
                          @if($getuser->idmoodle != null)
                            <a class="btn btn-warning btn-sm" href="/admin/user/{{$getuser->idmoodle}}/edit" title="Edit"><i class="fas fa-edit"></i></a>
                          @endif
                          &nbsp;
                          @if($getuser->idmoodle != null)
                          <form action="{{ route('user.destroy', $getuser->idmoodle) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete this course?')"><i class="fas fa-trash"></i></button>
                          </form>
                          @endif
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                  <tfoot>
                    <tr>
                      <th>No</th>
                      <th>Fullname</th>
                      <th>Email</th>
                      <th>Photo</th>
                      <th>Account Type</th>
                      <th>Level</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

@push('script')
  <script>
    $(function () {
      $('#datatables').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });
    });
  </script>
@endpush