routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\EnrolController;
use App\Http\Controllers\LMSController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\IndexController;
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('landingpage');
// });

Route::prefix('admin')->middleware(['auth','admin'])->group(function () {

    Route::get('/dashboard', [IndexController::class, 'index']);

    Route::resource('course', App\Http\Controllers\Admin\CourseController::class);

    Route::resource('category', App\Http\Controllers\Admin\CategoryController::class, ['only' => [
        'create', 'store', 'index'
    ]]);

    Route::resource('user', App\Http\Controllers\Admin\UserController::class);

});

Route::resource('catalog', CourseController::class, ['only' => [
    'index', 'show'
]]);

Route::get('/my', [CourseController::class, 'my'])->middleware('auth');
Route::get('/enrol/{id}', [EnrolController::class, 'enrol'])->middleware('auth');
Route::get('/', [LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/course/moodle/{id}', [LMSController::class, 'course'])->middleware('auth');
Route::get('/moodle/admin', [LMSController::class, 'admin'])->middleware('auth','verified');
Auth::routes();

resources/views/admin/courses/create.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'Create Course')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Create Course</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Create Course</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
                @if($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
                <form action="/admin/course" method="post">
					        {{ csrf_field() }}
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Category</label>
                    <div class="col-md-8">
                      <select class="select2" data-placeholder="Select category" name="idcategory" style="width: 100%;">
                        @foreach($category as $getcat)
                          <option value="{{$getcat->idcategory}}">{{$getcat->name}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Fullname</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="fullname" placeholder="" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Shortname</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="shortname" placeholder="" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Summary</label>
                    <div class="col-md-8">
                      <textarea class="form-control" rows="3" placeholder="" name="summary"></textarea>
                    </div>
                  </div>

                  <hr>
                  
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Topik</label>
                    <div class="col-md-8">
                      <textarea id="summernoteTopik" class="form-control" rows="3" placeholder="" name="topik"></textarea>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Tujuan</label>
                    <div class="col-md-8">
                      <textarea id="summernoteTujuan" class="form-control" rows="3" placeholder="" name="tujuan"></textarea>
                    </div>
                  </div>
                  <div class="form-group row">
                  <label class="col-md-3 col-form-label text-md-right">Video Teaser</label>
						      <div class="col-md-8 custom-file">
                      <input type="file" class="custom-file-input" id="customFile" name="video">
                      <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                  </div>
				  
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Durasi</label>
                    <div class="col-md-1">
                      <input class="form-control" type="text" name="durasi" placeholder="" required/>
                    </div>
                    <label class="col-md-1 col-form-label text-md-right">Level</label>
                    <div class="col-md-2">
                      <select class="select2" data-placeholder="Select category" name="level" style="width: 100%;">
                        <option value="Easy">Easy</option>
                        <option value="Medium">Medium</option>
                        <option value="Intermediate">Intermediate</option>
                      </select>
                    </div>
                    <label class="col-md-2 col-form-label text-md-right">Rekomendasi</label>
                    <div class="col-md-2">
                      <input class="form-control" type="text" name="rekomendasi" placeholder="" required/>
                    </div>
                  </div>
				  
				          <hr>

                  <div class="form-group row">
                    <label class="col-md-3 text-md-right">Visibility</label>
                    <div class="col-md-8 custom-control custom-switch" style="padding-left: 2.75rem;">
                      <input type="checkbox" class="custom-control-input" id="visibility" name="visible" value="1" checked>
                      <label class="custom-control-label" for="visibility">Visible</label>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Start Date</label>
                    <div class="col-md-8">
                        <input type="date" name="startdate" class="form-control" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">End Date</label>
                    <div class="col-md-8">
                        <input type="date" name="enddate" class="form-control" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 text-md-right">Availability</label>
                    <div class="col-md-8">
                      <select class="select2" name="availability" data-placeholder="Select model" style="width: 100%;">
                        <option value="Umum">Umum</option>
                        <option value="Private">Private</option>
                      </select>
					          </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Model</label>
                    <div class="col-md-8">
                      <select class="select2" name="model" data-placeholder="Select model" style="width: 100%;">
                        <option value="1">Elearning</option>
                        <option value="2">In Class</option>
						            <option value="3">Blended Learning</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Price</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="price" placeholder="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Accesscode</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="accesscode" placeholder="">
                    </div>
                  </div>
				  {{--
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Topik</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="topik" placeholder="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Durasi</label>
                    <div class="col-md-8">
                      <input class="form-control" type="number" name="durasi" placeholder="">
                    </div>
                    <span>
                    Jam
                    </span>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Level</label>
                    <div class="col-md-8">
                      <input class="form-control" type="number" name="level" placeholder="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Rekomendasi</label>
                    <div class="col-md-8">
                      <input class="form-control" type="number" name="rekomendasi" placeholder="">
                    </div>
                    <span>
                    Jam
                    </span>
                  </div>
				  --}}
                  <div class="form-group row" style="margin-bottom: 0;">
                    <div class="col-md-8 offset-md-3">
                      <input class="btn btn-primary" type="submit" value="Save Now">
                    </div>
                  </div>
                </form>
              </div>
            </div><!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

@push('script')
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()

      //Datemask dd/mm/yyyy
      $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
      $('[data-mask]').inputmask()
    });

  // Add the following code if you want the name of the file appear on select
  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
  </script>
@endpush

resources/views/admin/courses/edit.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'Update Course')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Update Course</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Update Course</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
                @if($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
                <form action="/admin/course/{{$course->idcourse}}" method="post" enctype="multipart/form-data">
                    @method('PUT')
					{{ csrf_field() }}
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Category</label>
                    <div class="col-md-8">
                      <select class="select2" data-placeholder="Select category" name="idcategory" style="width: 100%;">
						<option value="{{$course->category->idcategory}}" selected/>{{$course->category->name}}</option>
                        @foreach($category as $getcat)
                          <option value="{{$getcat->idcategory}}">{{$getcat->name}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Fullname</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="fullname" placeholder="" value="{{$course->fullname}}" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Shortname</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="shortname" placeholder="" value="{{$course->shortname}}" required/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Summary</label>
                    <div class="col-md-8">
                      <textarea id="summernoteSummary" class="form-control" rows="3" placeholder="" name="summary">{{$course->summary}}</textarea>
                    </div>
                  </div>
				  
				  <hr>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Topik</label>
                    <div class="col-md-8">
                      <textarea id="summernoteTopik" class="form-control" rows="3" placeholder="" name="topik">{{$course->topik}}</textarea>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Tujuan</label>
                    <div class="col-md-8">
                      <textarea id="summernoteTujuan" class="form-control" rows="3" placeholder="" name="tujuan">{{$course->tujuan}}</textarea>
                    </div>
                  </div>
				  <div class="form-group row">
                  <label class="col-md-3 col-form-label text-md-right">Video Teaser</label>
					<div class="col-md-8 custom-file">
                      <input type="file" class="custom-file-input" id="customFile" name="video" value="{{$course->video}}">
                      <label class="custom-file-label" for="customFile">{{$course->video}}</label>
                    </div>
                  </div>
				  
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Durasi</label>
                    <div class="col-md-1">
                      <input class="form-control" type="text" name="durasi" placeholder="" value="{{$course->durasi}}">
                    </div>
                    <label class="col-md-1 col-form-label text-md-right">Level</label>
                    <div class="col-md-2">
                      <select class="select2" data-placeholder="Select category" name="level" style="width: 100%;">
						<option value="{{$course->level}}" selected/>{{$course->level}}</option>
						<option value="Easy">Easy</option>
						<option value="Medium">Medium</option>
						<option value="Intermediate">Intermediate</option>
                      </select>
                    </div>
                    <label class="col-md-2 col-form-label text-md-right">Rekomendasi</label>
                    <div class="col-md-2">
                      <input class="form-control" type="text" name="rekomendasi" placeholder="" value="{{$course->rekomendasi}}">
                    </div>
                  </div>
				  <hr>
                  <div class="form-group row">
                    <label class="col-md-3 text-md-right">Visibility</label>
                    <div class="col-md-8 custom-control custom-switch" style="padding-left: 2.75rem;">
                      <input type="checkbox" class="custom-control-input" id="visibility" name="visible" value="1" {{$course->visible == '1' ? 'checked' : ''}}>
                      <label class="custom-control-label" for="visibility">Visible</label>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 text-md-right">Availability</label>
                    <div class="col-md-8">
                      <select class="select2" name="availability" data-placeholder="Select model" style="width: 100%;">
                        <option value="{{$course->availability == 'Umum' ? 'Umum' : 'Private'}}" selected/>{{$course->availability == 'Umum' ? 'Umum' : 'Private'}}</option>
                        <option value="Umum">Umum</option>
                        <option value="Private">Private</option>
                      </select>
					          </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Model</label>
                    <div class="col-md-8">
                      <select class="select2" name="model" data-placeholder="Select model" style="width: 100%;">
                        <option value="1">Elearning</option>
                        <option value="2">In Class</option>
						 <option value="3">Blended Learning</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Price</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="price" value="{{$course->price}}" placeholder="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-md-3 col-form-label text-md-right">Accesscode</label>
                    <div class="col-md-8">
                      <input class="form-control" type="text" name="accesscode" value="{{$course->accesscode}}"  placeholder="">
                    </div>
                  </div>
                  <div class="form-group row" style="margin-bottom: 0;">
                    <div class="col-md-8 offset-md-3">
                      <input class="btn btn-primary" type="submit" value="Save Now">
                    </div>
                  </div>
                </form>
              </div>
            </div><!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

@push('script')
  <script>

    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()

      //Datemask dd/mm/yyyy
      $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
      $('[data-mask]').inputmask()
    });
    
    $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
	
	
	$(function () {
		// Summernote
		$('#summernoteSummary').summernote()

		// CodeMirror
		CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
		  mode: "htmlmixed",
		  theme: "monokai"
		});
	  })
	$(function () {
		// Summernote
		$('#summernoteTopik').summernote()

		// CodeMirror
		CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
		  mode: "htmlmixed",
		  theme: "monokai"
		});
	  })
	$(function () {
		// Summernote
		$('#summernoteTujuan').summernote()

		// CodeMirror
		CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
		  mode: "htmlmixed",
		  theme: "monokai"
		});
	  })
  </script>
@endpush

resources/views/admin/courses/index.blade.php
@extends('admin.layouts.admin-app')

@section('title', 'List Courses')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">List Courses</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">List Courses</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-primary card-outline">
              <div class="card-body">
                @if(session()->has('message'))
                  <div class="alert alert-warning">
                    {{ session()->get('message') }}
                  </div>
                @endif
				<div class="table-responsive">
					<table id="datatables" class="table table-bordered table-striped">
					  <thead>
						<tr>
						  <th>ID</th>
						  <th>Category</th>
						  <th>Fullname</th>
						  <th>Shortname</th>
						  <th>Visible</th>
						  <th>Date</th>
						  <th>Availability</th>
						  <th>Model</th>
						  <th>Price</th>
						  <th>Code</th>
						  <th>Visible</th>
						  <th>Action</th>
						</tr>
					  </thead>
					  <tbody>
						@foreach($courses as $getcourse)
						  <tr>
							<td>{{$getcourse->idcourse}}</td>
							<td>{{get_name_category($getcourse->idcategory)}}</td>
							<td>{{$getcourse->fullname}}</td>
							<td>{{$getcourse->shortname}}</td>
							<td>{{$getcourse->visible}}</td>
							<td>{{$getcourse->start_date}} s.d {{$getcourse->end_date}}</td>
							<td>{{$getcourse->availability}}</td>
							<td>
							  @if($getcourse->model == '1')
								Elearning
							  @elseif($getcourse->model == '2')
								In Class
							  @elseif($getcourse->model == '3')
								Blended Learning
							  @endif
							</td>
							<td>{{$getcourse->price}}</td>
							<td>{{$getcourse->accesscode}}</td>
							<td>@if($getcourse->visible == '1')
									Show
								@else
									Hidden
								@endif
							</td>
							<td class="flex">
								<div class="btn-group ">
									<button type="button" class="btn btn-warning btn-xs">Action</button>
									<button type="button" class="btn btn-warning dropdown-toggle dropdown-icon" data-toggle="dropdown"></button>
									<span class="sr-only">Toggle Dropdown</span>
									<div class="dropdown-menu" role="menu">
										<a class="dropdown-item" href="/admin/enrolment/add/{{$getcourse->idcourse}}">Enroll</a>
										<a class="dropdown-item" href="/admin/course/moodle/{{$getcourse->idcourse}}">To Moodle</a>
										<a class="dropdown-item" href="/admin/course/certificate/{{$getcourse->idcourse}}">Certificate</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="/admin/course/{{$getcourse->idcourse}}/edit">Edit</a>
										<form action="{{ route('course.destroy', $getcourse->idcourse) }}" method="POST">
											@method('DELETE')
											@csrf
											<button class="dropdown-item" onclick="return confirm('Are you sure want to delete this course?')">Delete</button>
										</form>
									</div>
								</div>
							</td>
						  </tr>
						@endforeach
					  </tbody>
					</table>
				</div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

@push('script')
  <script>
    $(function () {
      $('#datatables').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": false,
        "info": true,
        "autoWidth": false,
      });
    });
  </script>
@endpush